export const ApplicationActions = {
  LOAD_APP_INITIAL_DATA: "LOAD_APP_INITIAL_DATA",
  ENTER_ACTIVE_STATE: "ENTER_ACTIVE_STATE",
  ENTER_BACKGROUND_STATE: "ENTER_BACKGROUND_STATE",
  ENTER_INACTIVE_STATE: "ENTER_INACTIVE_STATE",
  NETWORK_STATUS_CHANGE: "NETWORK_STATUS_CHANGE"
};

export const UserActions = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED"
};

export const Page_Actions = {
  PAGE_LOADING: "PAGE_LOADING",
  PAGE_LOADED: "PAGE_LOADED",
  UPDATE_NAV_HEADER: "UPDATE_NAV_HEADER",
  UPDATE_STACK_COUNT: "UPDATE_STACK_COUNT",
  TOGGLE_NAVIGATION_BAR: "TOGGLE_NAVIGATION_BAR"
};

export const UserLeaveActions = {
  GET_LEAVE_STATISTICS: "GET_LEAVE_STATISTICS",
  GET_HOLIDAY_LIST: "GET_HOLIDAY_LIST",
  GET_LEAVE_HISTORY: "GET_LEAVE_HISTORY",
  ERROR_WHILE_FETCHING_LEAVE_DATA: "ERROR_WHILE_FETCHING_LEAVE_DATA"
};

export const UserAttendanceActions = {
  GET_USER_ATTENDANCE:"GET_USER_ATTENDANCE",
  ERROR_WHILE_FETCHING_ATTENDANCE_DATA: "ERROR_WHILE_FETCHING_ATTENDANCE_DATA"
};

export const AlertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR"
};
